name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NVCC_FLAGS: "-allow-unsupported-compiler --threads 1"
  TORCH_CUDA_ARCH_LIST: "7.0;7.5+PTX;8.0;8.6+PTX"
  DISTUTILS_USE_SDK: 1
  FORCE_CUDA: 1

jobs:
  build:
    runs-on: ${{ matrix.os-version }}
    
    strategy:
      fail-fast: false
      matrix:
        os-version: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.8']
        include:
          - python-version: '3.10'
            cuda-version: '11.3.1'
            torch-install-command: 'torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113'
          - python-version: '3.8'
            cuda-version: '11.7.0'
            torch-install-command: 'torch==1.13.0+cu117 torchvision==0.14.0+cu117 --extra-index-url https://download.pytorch.org/whl/cu117'

    steps:
      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ilammy/msvc-dev-cmd@v1
        id: msvc
        with:
          vsversion: 2022
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
      - id: building
        env:
          CUDA_HOME: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
        run: |
          git clone https://github.com/facebookresearch/xformers.git
          cd xformers
          git submodule update --init --recursive
          pip install ${{ matrix.torch-install-command }}
          pip install -r requirements.txt
          pip install wheel
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: xformers-wheel-${{ matrix.os-version }}-${{ matrix.python-version }}-${{ matrix.cuda-version }}
          path: xformers/dist/*.whl
